# Smooooth Operator — developer entrypoints.
# All targets must stay green on Linux; see docs/TESTING.md.

SWIFT ?= swift
DENO ?= deno
SUPABASE ?= supabase

.PHONY: test kit-test db-test edge-test xval regen-goldens syntax-check lint

## Run every Linux-verifiable test suite (the definition of "green").
test: kit-test db-test edge-test syntax-check

## SwiftPM package: build + unit/property/golden tests.
kit-test:
	cd SmoooothKit && $(SWIFT) build && $(SWIFT) test

## pgTAP schema + RLS tests against the local Supabase stack.
db-test:
	$(SUPABASE) test db

## Edge function unit tests (scoring/integrity TS ports, contracts).
edge-test:
	cd supabase/functions && $(DENO) test --allow-read=../../fixtures,../../configs

## End-to-end: golden run through storage + score-run against the LOCAL stack
## (requires `supabase start`; skips itself when the stack is down).
e2e-test:
	cd supabase/functions && $(DENO) test --allow-read=../../fixtures,../../configs --allow-net \
		tests/score_run_integration_test.ts \
		tests/course_creation_integration_test.ts \
		tests/delete_account_integration_test.ts

## Cross-validate Swift reference scorer against the TS port on all golden vectors.
xval:
	tools/xval.sh

## Regenerate golden fixtures via sogen. Deliberate act — review the diff.
regen-goldens:
	tools/regen-goldens.sh

## Parse-check the iOS layer on Linux (no type resolution — see docs/TESTING.md).
syntax-check:
	tools/ios-syntax-check.sh
	tools/a11y-check.sh
	tools/web-escaping-check.sh

## Enforce Kit purity: no Apple-only framework imports in SmoooothKit.
lint:
	tools/kit-purity-check.sh

# The course-creation contract spans Swift and TypeScript. This fixture is
# GENERATED by the Swift builder so the server test checks what the app
# actually sends, not a hand-written copy that drifts.
regen-course-contract:
	cd SmoooothKit && swift run sogen course-proposal --metres 6000 --curviness 0.04 --seed 7 \
		> ../fixtures/contracts/course_proposal.json
	@echo "regenerated fixtures/contracts/course_proposal.json"

# The upload contract spans Swift and TypeScript at its most consequential
# point: the phone gzips a blob and declares a hash, and the server refuses
# to score anything whose hash does not match. This fixture is GENERATED by
# the Swift uploader's own code path so the Deno test checks what the app
# really sends.
regen-telemetry-contract:
	cd SmoooothKit && swift run sogen telemetry-blob --profile normal --seed 3 \
		> ../fixtures/contracts/telemetry_blob.json
	@echo "regenerated fixtures/contracts/telemetry_blob.json"

# Swift ghosts for every golden vector. The goldens carry no ghost data, so
# without this the ghost port — the moat — is cross-validated by nothing.
regen-ghost-xval:
	cd SmoooothKit && swift run sogen ghost-xval --fixtures ../fixtures/golden \
		> ../fixtures/contracts/ghost_xval.json
	@echo "regenerated fixtures/contracts/ghost_xval.json"
