import Foundation
import SOCore
import SOSimulator
import SOSync
import SOTelemetry

/// Emits a real gzipped telemetry blob, exactly as the app uploads one, so
/// the server can be tested against Swift's actual output.
///
/// The upload path crosses a language boundary at its most consequential
/// point: the phone gzips a blob and declares a sha256, and `score-run`
/// refuses to score anything whose hash does not match. Before this, the
/// TypeScript half was tested against a hand-written fixture — which is to
/// say the compression, the hash semantics and the wire format were checked
/// by nobody, on the one path where a mismatch loses a drive somebody did.
///
/// Same pattern as `course-proposal`: generate from the Swift side, assert
/// from the TypeScript side.
enum TelemetryBlobDump {
    static func emit(profile: SimulationProfile, seed: UInt64) -> String {
        let simulator = TelemetrySimulator(profile: profile, seed: seed)
        let run = simulator.simulate(route: TelemetrySimulator.demoRoute(seed: seed))

        let upload: TelemetryBlob.Upload
        let json: Data
        do {
            json = try TelemetryBlob.encode(gps: run.gps, imu: run.imu)
            upload = try TelemetryBlob.upload(gps: run.gps, imu: run.imu)
        } catch {
            return "{\"error\": \"\(error)\"}"
        }

        // The expectations below are Swift's OWN reading of these exact
        // bytes, not the in-memory samples they came from. That is the point:
        // when the Deno side asserts the same values, what has been proven is
        // that two independent readers agree on one blob — which is the
        // actual contract. Comparing against the unrounded originals would
        // only re-test the quantiser.
        let decoded: (gps: [GPSSample], imu: [IMUSample])
        do {
            decoded = try TelemetryBlob.decode(json)
        } catch {
            return "{\"error\": \"\(error)\"}"
        }

        // The first and last samples are carried separately so the Deno side
        // can assert it decoded the *same* drive, not merely something that
        // parsed. A wire format that silently reorders or truncates still
        // produces valid JSON.
        let payload: [String: Any] = [
            "note": "Generated by `sogen telemetry-blob`. Do not hand-edit — "
                + "run `make regen-telemetry-contract`.",
            "profile": profile.rawValue,
            "seed": Int(seed),
            "formatVersion": TelemetryBlob.formatVersion,
            "absentSentinel": TelemetryBlob.absent,
            // The envelope's sha256 is over the COMPRESSED bytes, because
            // that is what the server fetches and hashes before it
            // decompresses anything. Getting this backwards fails every run.
            "sha256": upload.sha256,
            "gzipBase64": upload.bytes.base64EncodedString(),
            "compressedBytes": upload.byteSize,
            "uncompressedBytes": upload.uncompressedByteSize,
            "expected": [
                "gpsCount": decoded.gps.count,
                "imuCount": decoded.imu.count,
                "sha256OfUncompressed": SHA256Digest.hex(of: json),
                "firstGps": [
                    decoded.gps[0].timestamp,
                    decoded.gps[0].coordinate.latitude,
                    decoded.gps[0].coordinate.longitude,
                ],
                "lastGps": [
                    decoded.gps[decoded.gps.count - 1].timestamp,
                    decoded.gps[decoded.gps.count - 1].coordinate.latitude,
                    decoded.gps[decoded.gps.count - 1].coordinate.longitude,
                ],
                "firstImu": [
                    decoded.imu[0].timestamp, decoded.imu[0].accelX,
                    decoded.imu[0].accelY, decoded.imu[0].accelZ,
                ],
            ],
        ]
        let data = try! JSONSerialization.data(
            withJSONObject: payload, options: [.sortedKeys, .prettyPrinted]
        )
        return String(data: data, encoding: .utf8)!
    }
}
