// Course creation spans two languages: Swift builds the proposal on the
// phone, TypeScript validates and inserts it on the server. A contract
// nobody checks is a contract that breaks on a real device — and the driver
// would see "invalid course" for a road they had just driven.
//
// The fixture here is generated BY the Swift builder (`sogen
// course-proposal`), not written by hand, so it cannot drift from what the
// app actually sends.

import { assert, assertEquals } from "jsr:@std/assert@1";
import { validateCourse } from "../_shared/pipeline/validator.ts";
import type { Checkpoint } from "../_shared/pipeline/types.ts";
import type { GeoCoordinate } from "../_shared/pipeline/geo.ts";

const proposal = JSON.parse(
  await Deno.readTextFile(
    new URL("../../../fixtures/contracts/course_proposal.json", import.meta.url),
  ),
) as {
  name: string;
  visibility: string;
  difficulty: number;
  polyline: [number, number][];
  checkpoints: [number, number, number, number][];
};

function toPolyline(): GeoCoordinate[] {
  return proposal.polyline.map(([latitude, longitude]) => ({ latitude, longitude }));
}

function toCheckpoints(): Checkpoint[] {
  return proposal.checkpoints.map(([sequence, latitude, longitude, radiusMeters]) => ({
    sequence,
    center: { latitude, longitude },
    radiusMeters,
  }));
}

Deno.test("what the Swift builder produces, the TypeScript validator accepts", () => {
  // The single most important assertion in the creation flow. If this ever
  // fails, drivers are being told a road they drove is not a valid course.
  const issues = validateCourse(toPolyline(), toCheckpoints());
  assertEquals(issues, [], `server rejected a real recorded drive: ${JSON.stringify(issues)}`);
});

Deno.test("the proposal carries what the endpoint requires", () => {
  assert(typeof proposal.name === "string" && proposal.name.length >= 3);
  assert(["public", "friends", "private"].includes(proposal.visibility));
  assert(proposal.difficulty >= 1 && proposal.difficulty <= 5);
  assert(proposal.polyline.length >= 2, "a course needs a route");
  assertEquals(proposal.checkpoints.length, 5, "five gates, matching the catalog");
});

Deno.test("gate rows are [sequence, lat, lon, radius] in order", () => {
  // Positional encoding is easy to get subtly wrong across a language
  // boundary — lat/lon swapped produces a course on the other side of the
  // world that still validates as geometry.
  proposal.checkpoints.forEach(([sequence, lat, lon, radius], index) => {
    assertEquals(sequence, index, "sequences must be contiguous from zero");
    assert(Math.abs(lat) <= 90, `latitude out of range: ${lat}`);
    assert(Math.abs(lon) <= 180, `longitude out of range: ${lon}`);
    assert(radius > 0 && radius <= 200, `implausible gate radius: ${radius}`);
  });
});

Deno.test("the route is in latitude/longitude order, not the reverse", () => {
  // Swapped pairs would place a Los Angeles course in the Indian Ocean and
  // still pass every geometric rule.
  for (const [lat, lon] of proposal.polyline) {
    assert(Math.abs(lat) <= 90, `latitude out of range: ${lat}`);
    assert(Math.abs(lon) <= 180, `longitude out of range: ${lon}`);
  }
});

Deno.test("no segment exceeds the spacing the validator allows", () => {
  const points = toPolyline();
  for (let i = 0; i + 1 < points.length; i++) {
    const a = points[i], b = points[i + 1];
    const dLat = (b.latitude - a.latitude) * 111_320;
    const dLon = (b.longitude - a.longitude) * 111_320 *
      Math.cos(a.latitude * Math.PI / 180);
    const metres = Math.hypot(dLat, dLon);
    assert(metres <= 500, `gap of ${metres.toFixed(0)} m between points ${i} and ${i + 1}`);
  }
});
