// End-to-end course creation against the LIVE local stack: the exact JSON
// the app posts → handleValidateCourse → Pro gate → shared validator →
// service-role insert → a course another driver can find.
//
// The unit test proves the geometry validates. This proves the ENDPOINT
// accepts it — shape checks, entitlement, insert, and the gates landing in
// their own table. Those are different things, and only this one is the
// call path a driver actually takes.
//
// Skips itself when the stack is unavailable so unit-only runs stay green.

import { assert, assertEquals } from "jsr:@std/assert@1";
import { handleValidateCourse } from "../validate-course/index.ts";

const SUPABASE_URL = "http://127.0.0.1:54321";
const SERVICE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU";

const netAllowed = (await Deno.permissions.query({ name: "net" })).state === "granted";
let stackUp = false;
if (netAllowed) {
  try {
    const probe = await fetch(`${SUPABASE_URL}/rest/v1/`, {
      headers: { apikey: SERVICE_KEY },
    });
    await probe.body?.cancel();
    stackUp = probe.status < 500;
  } catch {
    stackUp = false;
  }
}

const headers = {
  apikey: SERVICE_KEY,
  Authorization: `Bearer ${SERVICE_KEY}`,
  "Content-Type": "application/json",
};

const rest = (path: string, init?: RequestInit) =>
  fetch(`${SUPABASE_URL}/rest/v1${path}`, {
    ...init,
    headers: { ...headers, ...(init?.headers ?? {}) },
  });

const deps = { restUrl: `${SUPABASE_URL}/rest/v1`, serviceKey: SERVICE_KEY };

/** The exact payload the app builds, generated by the Swift builder. */
const proposal = JSON.parse(
  await Deno.readTextFile(
    new URL("../../../fixtures/contracts/course_proposal.json", import.meta.url),
  ),
);

const PRO_USER = "cc000001-a000-4000-8000-000000000001";
const FREE_USER = "cc000002-b000-4000-8000-000000000002";

async function seedDrivers() {
  for (const [id, email] of [[PRO_USER, "creator@test.local"], [FREE_USER, "free@test.local"]]) {
    await fetch(`${SUPABASE_URL}/auth/v1/admin/users`, {
      method: "POST",
      headers,
      body: JSON.stringify({ id, email, password: "course-creation-test", email_confirm: true }),
    }).then((r) => r.body?.cancel());
  }
  // Only one of them pays.
  await rest("/subscriptions", {
    method: "POST",
    headers: { Prefer: "resolution=merge-duplicates" },
    body: JSON.stringify({
      user_id: PRO_USER,
      product_id: "smooooth.pro.monthly",
      original_transaction_id: "course-create-pro",
      latest_transaction_id: "course-create-pro",
      status: "active",
      environment: "production",
      expires_at: new Date(Date.now() + 30 * 864e5).toISOString(),
    }),
  }).then((r) => r.body?.cancel());
}

async function cleanup(courseId?: string) {
  if (courseId) {
    await rest(`/course_checkpoints?course_id=eq.${courseId}`, { method: "DELETE" })
      .then((r) => r.body?.cancel());
    await rest(`/courses?id=eq.${courseId}`, { method: "DELETE" }).then((r) => r.body?.cancel());
  }
  await rest(`/subscriptions?original_transaction_id=eq.course-create-pro`, { method: "DELETE" })
    .then((r) => r.body?.cancel());
  for (const id of [PRO_USER, FREE_USER]) {
    await fetch(`${SUPABASE_URL}/auth/v1/admin/users/${id}`, { method: "DELETE", headers })
      .then((r) => r.body?.cancel());
  }
}

Deno.test({
  name: "e2e: a recorded drive becomes a course another driver can find",
  ignore: !stackUp,
  async fn() {
    await seedDrivers();
    let courseId: string | undefined;
    try {
      const result = await handleValidateCourse(
        { ...proposal, name: "Integration Test Road" },
        PRO_USER,
        deps,
      );
      assertEquals(result.status, 200, `endpoint refused a real drive: ${JSON.stringify(result.body)}`);
      courseId = result.body.courseId as string;
      assert(courseId, "no course id returned");

      // The row exists, is active, and carries derived catalog fields.
      const row = await (await rest(
        `/courses?id=eq.${courseId}&select=name,status,distance_meters,turn_count,benchmark_seconds,creator_id,visibility`,
      )).json();
      assertEquals(row.length, 1, "the course was not inserted");
      assertEquals(row[0].name, "Integration Test Road");
      assertEquals(row[0].status, "active");
      assertEquals(row[0].creator_id, PRO_USER, "the creator must own it");
      assert(row[0].distance_meters > 1000, "distance was not derived");

      // The benchmark trigger from migration 0021 must have fired, or every
      // run on this course would score zero pace.
      assert(
        row[0].benchmark_seconds > 0,
        "a user course was created with no benchmark — every run on it scores zero pace",
      );
      const impliedKmh = row[0].distance_meters / row[0].benchmark_seconds * 3.6;
      assert(
        impliedKmh >= 45 && impliedKmh <= 88,
        `derived benchmark implies ${impliedKmh.toFixed(1)} km/h, outside the catalog's range`,
      );

      // The gates landed in their own table, in order.
      const gates = await (await rest(
        `/course_checkpoints?course_id=eq.${courseId}&select=sequence&order=sequence`,
      )).json();
      assertEquals(gates.length, 5, "five gates should have been inserted");
      assertEquals(gates.map((g: { sequence: number }) => g.sequence), [0, 1, 2, 3, 4]);

      // And it is reachable through the query Explore actually uses.
      const nearby = await (await rest("/rpc/courses_near", {
        method: "POST",
        body: JSON.stringify({
          origin_lat: proposal.polyline[0][0],
          origin_lon: proposal.polyline[0][1],
          radius_meters: 5000,
        }),
      })).json();
      assert(
        nearby.some((c: { id: string }) => c.id === courseId),
        "the new course is not findable in Explore",
      );
    } finally {
      await cleanup(courseId);
    }
  },
});

Deno.test({
  name: "e2e: a free driver cannot create a course",
  ignore: !stackUp,
  async fn() {
    await seedDrivers();
    try {
      const result = await handleValidateCourse(
        { ...proposal, name: "Should Not Exist" },
        FREE_USER,
        deps,
      );
      assertEquals(result.status, 403, "the Pro gate did not hold");
      assertEquals(result.body.error, "pro_required");

      const rows = await (await rest("/courses?name=eq.Should Not Exist&select=id")).json();
      assertEquals(rows.length, 0, "a refused course was inserted anyway");
    } finally {
      await cleanup();
    }
  },
});

Deno.test({
  name: "e2e: geometry that fails validation is never inserted",
  ignore: !stackUp,
  async fn() {
    await seedDrivers();
    try {
      // A 40 m "course" — the validator's tooShort rule.
      const result = await handleValidateCourse(
        {
          name: "Car Park Sprint",
          visibility: "public",
          difficulty: 3,
          polyline: [[34.0, -118.0], [34.0004, -118.0]],
          checkpoints: [
            [0, 34.0, -118.0, 45],
            [1, 34.0004, -118.0, 45],
          ],
        },
        PRO_USER,
        deps,
      );
      assert(result.status >= 400, "a 40 m course was accepted");

      const rows = await (await rest("/courses?name=eq.Car Park Sprint&select=id")).json();
      assertEquals(rows.length, 0, "an invalid course reached the catalog");
    } finally {
      await cleanup();
    }
  },
});

Deno.test({
  name: "e2e: a malformed payload is refused before any write",
  ignore: !stackUp,
  async fn() {
    await seedDrivers();
    try {
      for (const bad of [
        { name: 123, visibility: "public", polyline: [], checkpoints: [] },
        { name: "No Visibility", visibility: "everyone", polyline: [], checkpoints: [] },
      ]) {
        // deno-lint-ignore no-explicit-any
        const result = await handleValidateCourse(bad as any, PRO_USER, deps);
        assertEquals(result.status, 400, `accepted malformed payload: ${JSON.stringify(bad)}`);
      }
    } finally {
      await cleanup();
    }
  },
});
