// Cross-validation for the ghost port (ADR-0002).
//
// The golden `expected.json` vectors carry scores, flags and verdicts —
// **not ghosts**. That left `ghost.ts` verified by nothing at all, on the
// part of the product that is the competitive moat. Three separate changes
// were made to it in one day with no check that the two implementations
// still agreed.
//
// A divergence here is invisible from the app: the phone would use its own
// Swift clock and the server would store a ghost built by different rules,
// so a driver racing their own best run would be shown a gap that is pure
// implementation difference — the exact defect that took a day to find and
// fix, reintroduced on the server only.
//
// Fixture is generated by `sogen ghost-xval` from the SAME golden telemetry
// the scoring vectors use, so it cannot drift from the Swift reference.
// Regenerate with `make regen-ghost-xval`.

import { assert, assertEquals } from "jsr:@std/assert@1";
import { generateGhost } from "../_shared/pipeline/ghost.ts";
import { processTrajectory } from "../_shared/pipeline/trajectory.ts";
import type { Checkpoint } from "../_shared/pipeline/types.ts";
import type { GeoCoordinate } from "../_shared/pipeline/geo.ts";

const ABSENT = -9999;

interface SwiftGhost {
  vector: string;
  totalSeconds?: number;
  points?: { progress: number; elapsedSeconds: number }[];
  ghost?: null;
}

const expected: SwiftGhost[] = JSON.parse(
  await Deno.readTextFile(
    new URL("../../../fixtures/contracts/ghost_xval.json", import.meta.url),
  ),
);

function loadTelemetry(vector: string) {
  const raw = JSON.parse(
    Deno.readTextFileSync(new URL(`../../../fixtures/golden/${vector}`, import.meta.url)),
  );
  const route: GeoCoordinate[] = raw.route.map(([latitude, longitude]: number[]) => ({
    latitude,
    longitude,
  }));
  const gates: Checkpoint[] = raw.gates.map(
    ([sequence, latitude, longitude, radiusMeters]: number[]) => ({
      sequence,
      center: { latitude, longitude },
      radiusMeters,
    }),
  );
  // Positional rows, same order as GoldenVector's Swift decoder:
  // [timestamp, lat, lon, horizontalAccuracy, course, speed, altitude]
  const gps = raw.gps.map((row: number[]) => ({
    timestamp: row[0],
    coordinate: { latitude: row[1], longitude: row[2] },
    horizontalAccuracy: row[3],
    course: row[4] === ABSENT ? null : row[4],
    speed: row[5] === ABSENT ? null : row[5],
    altitude: row[6] === ABSENT ? null : row[6],
  }));
  return { route, gates, gps };
}

assert(expected.length > 0, "no ghost cross-validation vectors — did sogen run?");

for (const swift of expected) {
  Deno.test(`ghost xval: ${swift.vector}`, () => {
    const { route, gates, gps } = loadTelemetry(swift.vector);
    // deno-lint-ignore no-explicit-any
    const trajectory = processTrajectory(gps as any);
    const actual = generateGhost(trajectory, route, gates);

    if (swift.points === undefined) {
      assertEquals(actual, null, "Swift produced no ghost; TypeScript produced one");
      return;
    }
    assert(actual !== null, "Swift produced a ghost; TypeScript produced none");

    // Total is what the whole race is measured against.
    assert(
      Math.abs(actual.totalSeconds - (swift.totalSeconds ?? 0)) < 1e-6,
      `totalSeconds diverged: swift ${swift.totalSeconds} vs ts ${actual.totalSeconds}`,
    );

    assertEquals(
      actual.points.length,
      swift.points.length,
      "point count diverged — the two ports downsample differently",
    );

    // Every point, not a sample of them: an interpolation that is right at
    // the ends and wrong in the middle is exactly what the last defect was.
    actual.points.forEach((point, index) => {
      const want = swift.points![index];
      assert(
        Math.abs(point.progress - want.progress) < 1e-9,
        `point ${index} progress: swift ${want.progress} vs ts ${point.progress}`,
      );
      assert(
        Math.abs(point.elapsedSeconds - want.elapsedSeconds) < 1e-6,
        `point ${index} elapsed: swift ${want.elapsedSeconds} vs ts ${point.elapsedSeconds}`,
      );
    });
  });
}

Deno.test("the ghost's ends are the progress the car actually had", () => {
  // Both ends used to be pinned — first to progress 0, last to 1.0 — and
  // neither is true. The fix must hold on BOTH sides or the clocks part
  // company again.
  for (const swift of expected) {
    if (!swift.points?.length) continue;
    const first = swift.points[0];
    const last = swift.points[swift.points.length - 1];
    assertEquals(first.elapsedSeconds, 0, `${swift.vector}: the clock starts at zero`);
    assert(
      first.progress >= 0 && first.progress < 0.05,
      `${swift.vector}: start progress ${first.progress} is not just past the gate`,
    );
    assert(
      last.progress > 0.5 && last.progress <= 1,
      `${swift.vector}: finish progress ${last.progress} is implausible`,
    );
  }
});
