// The upload contract, tested across both languages.
//
// The phone gzips a telemetry blob, declares a sha256, and the server
// refuses to score anything whose hash does not match. That handshake spans
// Swift and TypeScript at the most consequential point in the product: get
// it wrong and a drive somebody actually did is lost, with an error nobody
// sees until production.
//
// The fixture is GENERATED by the Swift uploader's own code path
// (`sogen telemetry-blob`, via `make regen-telemetry-contract`), so this
// tests what the app really sends rather than a hand-written copy that
// drifts. Same pattern as the course-proposal contract.

import { assert, assertAlmostEquals, assertEquals } from "jsr:@std/assert@1";
import { parseUpload, sha256Hex } from "../score-run/index.ts";

const fixture = JSON.parse(
  await Deno.readTextFile(
    new URL("../../../fixtures/contracts/telemetry_blob.json", import.meta.url),
  ),
);

function gzipBytes(): Uint8Array {
  const binary = atob(fixture.gzipBase64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return bytes;
}

/** Exactly what score-run does to a fetched blob, in the same order. */
async function decompress(bytes: Uint8Array): Promise<Uint8Array> {
  const stream = new Blob([bytes.slice().buffer as ArrayBuffer]).stream()
    .pipeThrough(new DecompressionStream("gzip"));
  return new Uint8Array(await new Response(stream).arrayBuffer());
}

Deno.test("telemetry contract: the blob Swift produces is gzip this runtime reads", async () => {
  const bytes = gzipBytes();
  // The magic score-run sniffs for before it decides to decompress.
  assertEquals(bytes[0], 0x1f);
  assertEquals(bytes[1], 0x8b);
  assertEquals(bytes[2], 0x08, "must be DEFLATE for DecompressionStream");
  const plain = await decompress(bytes);
  assertEquals(plain.byteLength, fixture.uncompressedBytes);
});

Deno.test("telemetry contract: the declared hash is over the COMPRESSED bytes", async () => {
  // The semantic most easily got backwards, and it would fail every run in
  // production while every local test passed: score-run hashes what it
  // fetched, before decompressing.
  assertEquals(await sha256Hex(gzipBytes()), fixture.sha256);

  const plain = await decompress(gzipBytes());
  assertEquals(await sha256Hex(plain), fixture.expected.sha256OfUncompressed);
  assert(
    fixture.sha256 !== fixture.expected.sha256OfUncompressed,
    "the two hashes must differ, or this test proves nothing",
  );
});

Deno.test("telemetry contract: Swift's SHA-256 agrees with Web Crypto", async () => {
  // SmoooothKit computes this digest with its own implementation, because
  // CryptoKit does not exist on Linux and the hash had to be testable. Two
  // independent implementations of SHA-256 must agree or no run ever scores.
  const plain = await decompress(gzipBytes());
  assertEquals(await sha256Hex(plain), fixture.expected.sha256OfUncompressed);
});

Deno.test("telemetry contract: the server parses it into the same drive", async () => {
  const plain = await decompress(gzipBytes());
  const json = JSON.parse(new TextDecoder().decode(plain));
  assertEquals(json.formatVersion, fixture.formatVersion);

  const { gps, imu } = parseUpload(json);
  assertEquals(gps.length, fixture.expected.gpsCount);
  assertEquals(imu.length, fixture.expected.imuCount);

  // Not merely "it parsed" — the same samples, in the same order. A format
  // that silently reordered or truncated would still produce valid JSON.
  //
  // Coordinates and accelerations are compared EXACTLY. They are written at
  // sensor resolution, so they are short decimal literals that every
  // conforming parser resolves to the same double.
  //
  // Timestamps are compared to 1 µs instead, and the reason is worth
  // recording: an absolute epoch second carries ~1.75e9 in front of the
  // fraction, which leaves a double about 2.4e-7 s of resolution. Swift's
  // JSON reader and V8's were measured to disagree by exactly that — one
  // ULP — on the same literal. Neither is wrong; the value is simply at the
  // edge of what the type holds. It is four orders of magnitude below the
  // millisecond that was measured to move a score, so it changes nothing
  // today. It is also the argument for making a future format version carry
  // time as an offset from the run's start, where the same double would hold
  // nanoseconds.
  const [t0, lat0, lon0] = fixture.expected.firstGps;
  assertAlmostEquals(gps[0].timestamp, t0, 1e-6);
  assertEquals(gps[0].coordinate.latitude, lat0);
  assertEquals(gps[0].coordinate.longitude, lon0);

  const [tLast, latLast, lonLast] = fixture.expected.lastGps;
  const last = gps[gps.length - 1];
  assertAlmostEquals(last.timestamp, tLast, 1e-6);
  assertEquals(last.coordinate.latitude, latLast);
  assertEquals(last.coordinate.longitude, lonLast);

  const [ti, ax, ay, az] = fixture.expected.firstImu;
  assertAlmostEquals(imu[0].timestamp, ti, 1e-6);
  assertEquals(imu[0].accelX, ax);
  assertEquals(imu[0].accelY, ay);
  assertEquals(imu[0].accelZ, az);
});

Deno.test("telemetry contract: absent readings arrive as null, not as zero", async () => {
  // -9999 is the sentinel both sides agree on. If the server read it as a
  // real value, a fix with no course would be scored as heading due north.
  const plain = await decompress(gzipBytes());
  const json = JSON.parse(new TextDecoder().decode(plain));
  const { gps } = parseUpload(json);

  for (const sample of gps) {
    assert(
      sample.course === null || sample.course !== fixture.absentSentinel,
      "the sentinel must never survive as a value",
    );
    assert(sample.speed === null || sample.speed !== fixture.absentSentinel);
    assert(
      sample.altitude === null || sample.altitude !== fixture.absentSentinel,
    );
  }
});

Deno.test("telemetry contract: written at sensor resolution, not Double resolution", async () => {
  // The saving is mostly here rather than in gzip: a full-precision Double
  // serialises seventeen significant digits, most of them floating-point
  // residue. Asserting the shape of the numbers keeps the two sides honest
  // about what is actually being sent.
  const plain = await decompress(gzipBytes());
  const json = JSON.parse(new TextDecoder().decode(plain));

  const decimals = (value: number) => {
    const text = String(value);
    const dot = text.indexOf(".");
    return dot < 0 ? 0 : text.length - dot - 1;
  };

  for (const row of json.gps.slice(0, 200)) {
    assert(decimals(row[1]) <= 7, `latitude ${row[1]} carries too many digits`);
    assert(decimals(row[2]) <= 7, `longitude ${row[2]} carries too many digits`);
    assert(decimals(row[3]) <= 2, `accuracy ${row[3]} carries too many digits`);
  }
  for (const row of json.imu.slice(0, 200)) {
    for (const axis of [1, 2, 3]) {
      assert(decimals(row[axis]) <= 5, `accel ${row[axis]} too many digits`);
    }
    for (const axis of [4, 5, 6]) {
      assert(decimals(row[axis]) <= 6, `gyro ${row[axis]} too many digits`);
    }
  }
});

Deno.test("telemetry contract: timestamps keep their precision", async () => {
  // Deliberately NOT rounded: at 10 Hz, one millisecond is 1% of the Δt that
  // speed and acceleration are derived from, and rounding them was measured
  // to move real scores (fastAggressive 8116 → 8112). See TelemetryBlob.
  const plain = await decompress(gzipBytes());
  const json = JSON.parse(new TextDecoder().decode(plain));
  const [expectedFirst] = fixture.expected.firstGps;
  assertAlmostEquals(json.gps[0][0], expectedFirst, 1e-6);

  // Intervals must still look like a 10 Hz feed rather than a rounded one.
  const deltas: number[] = [];
  for (let i = 1; i < Math.min(json.gps.length, 50); i++) {
    deltas.push(json.gps[i][0] - json.gps[i - 1][0]);
  }
  assert(
    deltas.some((d) => Math.abs(d - Math.round(d * 1000) / 1000) > 1e-9),
    "every interval landed exactly on a millisecond — timestamps look rounded",
  );
});

Deno.test("telemetry contract: the fixture is what the checked-in code produces", () => {
  // Guards against a fixture edited by hand or left behind by a format
  // change: these are the numbers `sogen telemetry-blob` reported.
  assertEquals(fixture.compressedBytes, gzipBytes().byteLength);
  assert(
    fixture.uncompressedBytes / fixture.compressedBytes > 3,
    `gzip ratio fell to ${fixture.uncompressedBytes / fixture.compressedBytes}`,
  );
});
